// Generado por scripts/update-heroes.mjs (npm run update:heroes). No editar a mano.
// Héroes de Deadlock: id → { name, image } (deadlock-api.com)
export const HEROES = {
  1: {"name":"Infernus","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/inferno_sm.webp"},
  2: {"name":"Siete","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/gigawatt_sm.webp"},
  3: {"name":"Vindicta","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/hornet_sm.webp"},
  4: {"name":"Lady Geist","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/spectre_sm.webp"},
  6: {"name":"Abrams","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/bull_sm.webp"},
  7: {"name":"Espectro","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/wraith_sm.webp"},
  8: {"name":"McGinnis","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/engineer_sm.webp"},
  10: {"name":"Paradoja","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/chrono_sm.webp"},
  11: {"name":"Dínamo","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/sumo_sm.webp"},
  12: {"name":"Kelvin","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/kelvin_sm.webp"},
  13: {"name":"Bruma","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/haze_sm.webp"},
  14: {"name":"Holliday","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/astro_sm.webp"},
  15: {"name":"Bebop","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/bebop_sm.webp"},
  16: {"name":"Felina","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/nano_sm.webp"},
  17: {"name":"Garra Gris","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/archer_sm.webp"},
  18: {"name":"Mo y Krill","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/digger_sm.webp"},
  19: {"name":"El Navajas","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/shiv_sm.webp"},
  20: {"name":"Hiedra","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/tengu_sm.webp"},
  25: {"name":"Guardia","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/warden_sm.webp"},
  27: {"name":"Yamato","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/yamato_sm.webp"},
  31: {"name":"Látigo","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/lash_sm.webp"},
  35: {"name":"Viscoso","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/viscous_sm.webp"},
  50: {"name":"Pocket","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/synth_sm.webp"},
  52: {"name":"Espejismo","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/mirage_sm.webp"},
  58: {"name":"Víbora","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/kali_sm.webp"},
  60: {"name":"Sinclair","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/magician_sm.webp"},
  63: {"name":"Mina","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/vampirebat_sm.webp"},
  64: {"name":"Vagabundo","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/drifter_sm.webp"},
  65: {"name":"Venator","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/priest_sm.webp"},
  66: {"name":"Víctor","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/frank_sm.webp"},
  67: {"name":"Paige","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/bookworm_sm.webp"},
  68: {"name":"Boho","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/hornet_sm.webp"},
  69: {"name":"El Portero","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/doorman_sm.webp"},
  70: {"name":"Skyrunner","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/skyrunner_sm.webp"},
  71: {"name":"Swan","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/swan_sm.webp"},
  72: {"name":"Billy","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/punkgoat_sm.webp"},
  74: {"name":"Graf","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/graf_sm.webp"},
  75: {"name":"Fortuna","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/fortuna_sm.webp"},
  76: {"name":"Graves","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/necro_sm.webp"},
  77: {"name":"Apolo","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/fencer_sm.webp"},
  79: {"name":"Rem","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/familiar_sm.webp"},
  80: {"name":"Silver","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/werewolf_sm.webp"},
  81: {"name":"Celeste","image":"https://assets-bucket.deadlock-api.com/assets-api-res/images/heroes/unicorn_sm.webp"},
};

export function heroInfo(id) {
  return HEROES[id] ?? { name: `Héroe #${id}`, image: null };
}
